// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9-nstHH5gi9mOcNr3ACFAwslQuicHtmM',
    appId: '1:1039048934045:web:b401c9369c0e81861d8a74',
    messagingSenderId: '1039048934045',
    projectId: 'mongoappv2',
    authDomain: 'mongoappv2.firebaseapp.com',
    storageBucket: 'mongoappv2.appspot.com',
    measurementId: 'G-R6627TM0RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_M_iVC8rYAgZDOKR9oW0wbiGdiZs7jiE',
    appId: '1:1039048934045:android:28e5c9beaeb4037a1d8a74',
    messagingSenderId: '1039048934045',
    projectId: 'mongoappv2',
    storageBucket: 'mongoappv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSwJrn4pek6nE9jdZ7JzPJ-Edd2R1y58',
    appId: '1:1039048934045:ios:adf4cf765b1458cf1d8a74',
    messagingSenderId: '1039048934045',
    projectId: 'mongoappv2',
    storageBucket: 'mongoappv2.appspot.com',
    androidClientId: '1039048934045-flkp5u25reu5mu5eq6fqcgqkp4aae1uq.apps.googleusercontent.com',
    iosClientId: '1039048934045-uvv5ee8hm87urv3q2400gjjjno424h6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mongoappv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSwJrn4pek6nE9jdZ7JzPJ-Edd2R1y58',
    appId: '1:1039048934045:ios:773a78693a5a53b41d8a74',
    messagingSenderId: '1039048934045',
    projectId: 'mongoappv2',
    storageBucket: 'mongoappv2.appspot.com',
    androidClientId: '1039048934045-flkp5u25reu5mu5eq6fqcgqkp4aae1uq.apps.googleusercontent.com',
    iosClientId: '1039048934045-vo424010ujuok857kalkrjj60165o98p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mongoappv2.RunnerTests',
  );
}
